---
- name: Deploying to GKE with Ansible
  hosts: localhost
  remote_user: hemant
  tasks:
    - name: Ensure python3-pip is installed
      package:
        name: python3-pip
        state: present

    - name: Install required Python packages
      pip:
        name:
          - google-auth
          - kubernetes
        executable: pip3
  
    - name: Install required collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install kubernetes.core google.cloud
      
    - name: Ensure GKE cluster is present
      google.cloud.gcp_container_cluster:
        name: coursemap-cluster-two
        zone: us-central1-c
        state: present
        project: gke-cluster-coursemap
        auth_kind: serviceaccount
        service_account_file: "~/gke-cluster-coursemap-4fec645c7f77.json"
      register: gke_cluster
    
    - name: Output of the above task
      debug:
        var: gke_cluster
    
    - name: Ensure that namespace is coursemap
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-namespace.yaml
        state: present

    # - name: Delete existing backend secret
    #   kubernetes.core.k8s:
    #     src: ./
    #     state: absent

    - name: Delete existing backend configmap
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend-configmap.yaml
        state: absent
        namespace: coursemap

    # - name: Delete existing frontend configmap
    #   kubernetes.core.k8s:
    #     src: ./
    #     state: absent

    - name: Delete existing backend deployment
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend.yaml
        state: absent
        namespace: coursemap

    - name: Delete existing frontend deployment
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-frontend.yaml
        state: absent
        namespace: coursemap

    - name: Delete existing backend nodeport service
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend-nodeport.yaml
        state: absent
        namespace: coursemap
    
    - name: Delete existing frontend loadbalancer service
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-frontend.yaml
        state: absent
        namespace: coursemap

# From here onwards, we will create all the resources needed for the application

    # - name: Create backend secret
    #   kubernetes.core.k8s:
    #     src: ./
    #     state: present
    #     apply: yes
    #     namespace: coursemap

    - name: Create backend configmap
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend-configmap.yaml
        state: present
        apply: yes
        namespace: coursemap

    # - name: Create frontend configmap
    #   kubernetes.core.k8s:
    #     src: ./
    #     state: present
    #     apply: yes
    #     namespace: coursemap

    - name: Create backend deployment
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend.yaml
        state: present
        apply: yes
        namespace: coursemap

    - name: Create frontend deployment
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-frontend.yaml
        state: present
        apply: yes
        namespace: coursemap

    - name: Create backend nodeport service
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-backend-nodeport.yaml
        state: present
        apply: yes
        namespace: coursemap
    
    - name: Create existing frontend loadbalancer service
      kubernetes.core.k8s:
        src: ./kubernetes/coursemap-frontend.yaml
        state: present
        apply: yes
        namespace: coursemap
