apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursemap-backend-deployment
  namespace: coursemap
spec:
  # Check Revision History Limit
  # Check if we can increase the number of replicas
  # Check if we can use a different strategy for rolling updates
  replicas: 1
  selector:
    matchLabels:
      app: coursemap-backend
  template:
    metadata:
      labels:
        app: coursemap-backend
    spec:
      containers:
      - name: backend
        image: hemantkumarcpersonal/coursemap-backend:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: Always
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: coursemap-backend-configmap
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: coursemap-backend-configmap
              key: MONGO_URI

---

apiVersion: v1
kind: Service
metadata:
  name: coursemap-backend-service
  namespace: coursemap
spec:
  selector:
    app: coursemap-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000