apiVersion: v1
kind: Service
metadata:
  name: coursemap-backend-nodeport
  namespace: coursemap
spec:
  type: NodePort
  selector:
    app: coursemap-backend
  ports:
    - name: http
      protocol: TCP
      port: 5000 # The port that the service will use inside the cluster
      targetPort: 5000 # The port on which your application is running inside the pods
      nodePort: 31995 # The port on the node that will be exposed externally (optional, otherwise automatically assigned)
